### PR TITLE
DI-435 CEN38 POP AF VCF

### PR DESCRIPTION
**Pull request by rklocke**
- Re-formatting, making re-usable, adding documentation and version controlling Win's Confluence code for creation of a 38 internal POP AF VCF: https://cuhbioinformatics.atlassian.net/wiki/spaces/DV/pages/3189244202/CEN38_POPAF_chr1-22_240503.vcf.gz
- Add READMEs

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/RD_requests/13)

### CODE REVIEW

**Review by RSWilson1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/RD_requests/13)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @rklocke)

___
*[`DI-435/find_vcfs_to_merge.py` line 164 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/13#-OB7AQjZAjr6GcoE5gBI:-OB7AQjZAjr6GcoE5gBJ:b-y7c09z) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b760937d7b9aba8b155d43fa861a2adbffca732f/DI-435/find_vcfs_to_merge.py#L164)):*
> ```Python
>         )
>         file_object.unarchive()
>         return
> ```

do we want this to return none here and not raise an error?
___
*[`DI-435/find_vcfs_to_merge.py` line 169 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/13#-OB7BUGy5gbCgD6D29PN:-OB7BUGy5gbCgD6D29PO:b-p1ed22) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b760937d7b9aba8b155d43fa861a2adbffca732f/DI-435/find_vcfs_to_merge.py#L169)):*
> ```Python
> 
> 
> def get_qc_files(b38_projects):
> ```

Note to self up to here.

**Review by RSWilson1 — CHANGES_REQUESTED** [review]
A few pep8 things.
Thanks for refactoring and improving looks a lot better!

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/RD_requests/13#-:-OBAYadyBO_I0Wc1pGpl:b13xf2l)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @rklocke)

___
*[`DI-435/merge_VCF_AF.sh` line 2 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/13#-OBAYgitCp40G9lyl7vP:-OBAYgitCp40G9lyl7vQ:b-sjuwzy) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b760937d7b9aba8b155d43fa861a2adbffca732f/DI-435/merge_VCF_AF.sh#L2)):*
> ```Shell
> #!/bin/bash
> # Script for merging VCF files and adding AF tag
> ```

nice comments
___
*[`DI-435/merge_VCF_AF.sh` line 59 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/13#-OBAY7z9BOm1gUJ2n7Hy:-OBAY7z9BOm1gUJ2n7Hz:bmdc5cc) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b760937d7b9aba8b155d43fa861a2adbffca732f/DI-435/merge_VCF_AF.sh#L59)):*
> ```Shell
> /home/dnanexus/bcftools-1.19/bcftools index merged.vcf.gz
> 
> export BCFTOOLS_PLUGINS=/home/dnanexus/bcftools-1.19/plugins/
> ```

This feels like something that should be at the start of the script?
___
*[`DI-435/find_vcfs_to_merge.py` line 19 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/13#-OBAXYIF6nGa8KW_mFQy:-OBAXYIF6nGa8KW_mFQz:b-8uox4q) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b760937d7b9aba8b155d43fa861a2adbffca732f/DI-435/find_vcfs_to_merge.py#L19)):*
> ```Python
>     """
>     parser = argparse.ArgumentParser(
>         description="Information required to find CEN VCFs"
> ```

Or TWE, maybe make this a bit more descriptive?
___
*[`DI-435/README.md` line 9 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/13#-OBAWKRt5zsYxOtPiAlf:-OBAWKRt5zsYxOtPiAlg:b-j92nxe) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b760937d7b9aba8b155d43fa861a2adbffca732f/DI-435/README.md#L9)):*
> ```Markdown
> The Python script `find_vcfs_to_merge.py` takes inputs:
> - `-a --assay`: The project prefix to look for in DNAnexus, e.g. `"*CEN38"`
> - `-o --outfile_name`: What to name the output TSV file which lists VCF files to merge
> ```

Would it make sense to have this as outfile_prefix and having a predefined name? And applying this to both output files?

**Review by rklocke — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/RD_requests/13#-:-OBAe1HT3h6fa4Uj_vLk:bnfp4nl)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @RSWilson1)

___
*[`DI-435/find_vcfs_to_merge.py` line 19 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/13#-OBAXYIF6nGa8KW_mFQy:-OBAadDq6QGKlNknvmxr:b-896fix) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b760937d7b9aba8b155d43fa861a2adbffca732f/DI-435/find_vcfs_to_merge.py#L19)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

Or TWE, maybe make this a bit more descriptive?
</blockquote></details>

Done.
___
*[`DI-435/find_vcfs_to_merge.py` line 164 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/13#-OB7AQjZAjr6GcoE5gBI:-OBAb4GnCCG3rqIH0LBB:b-nwyczy) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b760937d7b9aba8b155d43fa861a2adbffca732f/DI-435/find_vcfs_to_merge.py#L164)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

do we want this to return none here and not raise an error?
</blockquote></details>

this was mainly so that the script would run even if some QC status files were archived, I have re-formatted so it will gather all non-live files and unarchive them and exit which is probably better if this is used in future
___
*[`DI-435/merge_VCF_AF.sh` line 2 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/13#-OBAYgitCp40G9lyl7vP:-OBAafNp3oWsAM08ApYk:b-896fix) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b760937d7b9aba8b155d43fa861a2adbffca732f/DI-435/merge_VCF_AF.sh#L2)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

nice comments
</blockquote></details>

Done.
___
*[`DI-435/merge_VCF_AF.sh` line 59 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/13#-OBAY7z9BOm1gUJ2n7Hy:-OBAcIgY-Uc5-JOtosLk:b-75sdyb) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b760937d7b9aba8b155d43fa861a2adbffca732f/DI-435/merge_VCF_AF.sh#L59)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

This feels like something that should be at the start of the script?
</blockquote></details>

Very true, removed this and updated commands in the Confluence doc to install bcftools/htslib prior to running this script so this part and the full paths to both aren't needed here
___
*[`DI-435/README.md` line 9 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/13#-OBAWKRt5zsYxOtPiAlf:-OBAdg19ANfeJeaAOphE:b-py1twv) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b760937d7b9aba8b155d43fa861a2adbffca732f/DI-435/README.md#L9)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

Would it make sense to have this as outfile_prefix and having a predefined name? And applying this to both output files?
</blockquote></details>

Done, updated inputs and naming in Python script and README to reflect this

**Review by RSWilson1 — APPROVED** [review]
:lgtm:

> Dismissed @RSWilson1 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/RD_requests/13#-:-OBAvzqMDj0TlD3mEJe4:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved

___
*[`DI-435/find_vcfs_to_merge.py` line 164 at r1](https://reviewable.io/reviews/eastgenomics/RD_requests/13#-OB7AQjZAjr6GcoE5gBI:-OBAvlLFBlwQul9JquT5:b-47fafm) ([raw file](https://github.com/eastgenomics/RD_requests/blob/b760937d7b9aba8b155d43fa861a2adbffca732f/DI-435/find_vcfs_to_merge.py#L164)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

this was mainly so that the script would run even if some QC status files were archived, I have re-formatted so it will gather all non-live files and unarchive them and exit which is probably better if this is used in future
</blockquote></details>

looks good

**Review by RSWilson1 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/RD_requests/13)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Pull request merged**
